spring:
  application:
    name: busan
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: SPRING
    password: SPRING
    driver-class-name: oracle.jdbc.driver.OracleDriver
server:
  port: 80
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kh.busan.api.model.vo