spring:
  application:
    name: secom
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: SPRING
    password: SPRING
    driver-class-name: oracle.jdbc.driver.OracleDriver
server:
  port: 80

mybatis:
  configuration: 
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org.apache.ibatis: DEBUG
    java.sql: DEBUG
    jdbc.sqlonly: DEBUG
    jdbc.resultset: DEBUG
    jdbc.audit: DEBUG