spring:
  application:
    name: secom
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: BOOT
    password: BOOT
    driver-class-name: oracle.jdbc.driver.OracleDriver
  mvc:
    static-path-pattern: /uploads/**
  web:
    resources:
      static-locations: file:uploads/

server:
  port: 80

mybatis:
  configuration: 
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    jdbc-type-for-null: VARCHAR
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    org.apache.ibatis: DEBUG
    java.sql: DEBUG
    jdbc.sqlonly: DEBUG
    jdbc.resultset: DEBUG
    jdbc.audit: DEBUG

jwt:
  secret: H7oIaBujRo6fA/a0wdk09iY6STECQZbemMj8bcs5xBMzd0IYxzT+hNQd+fgXvsyz3qHF3DIwuYXUE9m7w5tkDw==